# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let 
  fwUpdate = config.my.hardware.firmwareUpdates.enable;
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # nvme: NVM Express https://nvmexpress.org/specifications/
  # xhci_pci: xHCI PCI Host Controller Driver 
  # uas: USB Attached storage
  # usbhid:  USB Human Interface Devices https://docs.kernel.org/input/input.html
  # sd_mod: SCSI disk (sd) driver
  
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ "amdgpu" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  hardware.cpu.amd.updateMicrocode = fwUpdate;
  hardware.enableAllFirmware = fwUpdate;             # enable all firmware updates regardless of license
  hardware.enableRedistributableFirmware = fwUpdate; # with license allowing redistribution
  #hardware.graphics.enable = true;
  hardware.pulseaudio = {
    enable = false;   # enable PulseAudio sound server
    #package = pulseaudioFull;  # pulseaudioFull includes extra features such as JAXK support & bluetooth
    systemWide = true; # if false, one pa server per user. if true, all users in group 'pulse-access' share server
  };  
}
